### ISSUE TITLE
ImportError: utilsos.module.so could not be located.

### ISSUE THREAD

**Issue by diamondspark** [conda-forge/scine-sparrow-python-feedstock#3] opened 2022-07-07 23:53 UTC
### Comment:

I tried 
```conda install -c conda-forge scine-sparrow-python```
I get ImportError: utilsos.module.so could not be located. when I try to import scine_sparrow. Following is the detailed error 
```
 python -c 'import scine_sparrow'
Could not load /home/mkpandey/anaconda3/envs/sparrow_test/lib/utilsos.module.so: locale::facet::_S_create_c_locale name not valid
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mkpandey/anaconda3/envs/sparrow_test/lib/python3.7/site-packages/scine_sparrow/__init__.py", line 7, in <module>
    import scine_utilities as utils
  File "/home/mkpandey/anaconda3/envs/sparrow_test/lib/python3.7/site-packages/scine_utilities/__init__.py", line 60, in <module>
    raise ImportError('{} could not be located.'.format(module_filename))
ImportError: utilsos.module.so could not be located.
```

Please help.

**Comment by awvwgk** [comment] 2022-07-08 08:44
Can you provide the output of `conda info` and `conda list`?

**Comment by awvwgk** [comment] 2022-07-20 09:50
Without further information and given that I cannot reproduce this on clean installation, I'm going to close this issue for now.

Feel free to reopen if the problem persists.

**Closed as completed by awvwgk** 2022-07-20 09:50 UTC
Labels: question
